# Generated by Django 4.1.7 on 2023-03-21 08:34
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloth", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
