# Generated by Django 4.1.7 on 2023-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloth", "0002_auto_20230321_0834"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cloth",
            options={
                "verbose_name": "Спец. одежда",
                "verbose_name_plural": "Спец. одежда",
            },
        ),
        migrations.AlterModelOptions(
            name="profession",
            options={"verbose_name": "Профессия", "verbose_name_plural": "Профессии"},
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=models.CharField(max_length=800, verbose_name="Название провессии"),
        ),
    ]
